//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysBank.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Document
    {
        public Application_Document()
        {
            this.Insurance = new HashSet<Insurance>();
        }
    
        public int Id { get; set; }
        public string Status { get; set; }
        public string Path { get; set; }
        public string File_Name { get; set; }
        public System.DateTime Application_Date { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Insurance> Insurance { get; set; }
    }
}
