
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SysBank.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class CreditCard
{

    public int Id { get; set; }

    public decimal Limit { get; set; }

    public int GracePeriod { get; set; }

    public decimal Provision { get; set; }

    public decimal InterestRate { get; set; }

    public decimal Debit { get; set; }

    public int BaseCardId { get; set; }

    public bool IsContactless { get; set; }

    public int GracePeriodCount { get; set; }

    public decimal MinimalRepayment { get; set; }



    public virtual PaymentCards PaymentCards { get; set; }

}

}
