//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysBank.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositType
    {
        public DepositType()
        {
            this.Deposites = new HashSet<Deposites>();
        }
    
        public int Id { get; set; }
        public string DepositName { get; set; }
        public decimal Interest { get; set; }
        public decimal MinimumAmount { get; set; }
        public bool IsRenewable { get; set; }
        public bool IsDynamic { get; set; }
        public int DurationInMonths { get; set; }
        public int CapitalizationnsPerYear { get; set; }
    
        public virtual ICollection<Deposites> Deposites { get; set; }
    }
}
