
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SysBank.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class DictionaryItems
{

    public DictionaryItems()
    {

        this.PaymentCardApplication = new HashSet<PaymentCardApplication>();

        this.PaymentCards = new HashSet<PaymentCards>();

        this.PaymentCardsOperationHistory = new HashSet<PaymentCardsOperationHistory>();

        this.PaymentCardsOperationHistory1 = new HashSet<PaymentCardsOperationHistory>();

        this.PaymentCardApplication1 = new HashSet<PaymentCardApplication>();

    }


    public int Id { get; set; }

    public int DictionaryId { get; set; }

    public string Value { get; set; }



    public virtual Dictionaries Dictionaries { get; set; }

    public virtual ICollection<PaymentCardApplication> PaymentCardApplication { get; set; }

    public virtual ICollection<PaymentCards> PaymentCards { get; set; }

    public virtual ICollection<PaymentCardsOperationHistory> PaymentCardsOperationHistory { get; set; }

    public virtual ICollection<PaymentCardsOperationHistory> PaymentCardsOperationHistory1 { get; set; }

    public virtual ICollection<PaymentCardApplication> PaymentCardApplication1 { get; set; }

}

}
