
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SysBank.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class PaymentCards
{

    public PaymentCards()
    {

        this.ATMCard = new HashSet<ATMCard>();

        this.CreditCard = new HashSet<CreditCard>();

        this.DebitCard = new HashSet<DebitCard>();

        this.PaymentCardsOperationHistory = new HashSet<PaymentCardsOperationHistory>();

    }


    public int Id { get; set; }

    public bool IsBlocked { get; set; }

    public int PIN { get; set; }

    public string CardNumber { get; set; }

    public System.DateTime CreationDate { get; set; }

    public System.DateTime ExpirationDate { get; set; }

    public string CardSecurityCode { get; set; }

    public int TypeId { get; set; }

    public string UserId { get; set; }



    public virtual AspNetUsers AspNetUsers { get; set; }

    public virtual ICollection<ATMCard> ATMCard { get; set; }

    public virtual ICollection<CreditCard> CreditCard { get; set; }

    public virtual ICollection<DebitCard> DebitCard { get; set; }

    public virtual DictionaryItems DictionaryItems { get; set; }

    public virtual ICollection<PaymentCardsOperationHistory> PaymentCardsOperationHistory { get; set; }

}

}
